server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/for-tests
    username: root
    password: root
  elasticsearch:
    uris: localhost:9300
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true